<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot"  >
<!-- property of base link-->
<xacro:property name="higth" value="0.16 "/>
<xacro:property name="width" value="0.6"/>
<xacro:property name="length" value="1"/>
<!-- property of base link -->
<xacro:property name="base_link_length" value="0.02"/>
<xacro:property name="base_link_radius" value="0.15"/>  
<!-- property of right wheel-->
<xacro:property name="wheel_radius" value="0.04"/>
<xacro:property name="right_wheel_length" value="0.04"/>
<xacro:property name="right_wheel_radius" value="0.14"/>
<xacro:property name="right_wheel_rpy" value="1.57"/>
<xacro:property name="right_joint_x" value="0.3"/>
<xacro:property name="right_joint_y" value="0.22"/>
<!-- property of left wheel-->
<xacro:property name="left_wheel_length" value="0.04"/>
<xacro:property name="left_wheel_radius" value="0.14"/>
<xacro:property name="left_wheel_rpy" value="1.57"/>
<xacro:property name="left_joint_x" value="0.3"/>
<xacro:property name="left_joint_y" value="0.22"/>
<!-- property of wheel axes-->
<xacro:property name= "wheel_axes" value="1"/>
<!-- property of limit-->
<xacro:property name="effort" value="300"/>
<xacro:property name="velocity" value="0.5"/>
<xacro:property name="lower" value="-3.14"/>
<xacro:property name="upper" value="3.14"/>
<!-- property of caster-->
<xacro:property name="caster_radius" value="0.06"/>
<xacro:property name="caster_joint_y" value="0.4"/>
<xacro:property name="caster_joint_z" value="0.08"/>
<!--property of moment inertial-->
<xacro:property name="mass" value="5"/>
<xacro:property name="ixx" value="0.01"/>
<xacro:property name="iyy" value="0.01"/>
<xacro:property name="izz" value="0.01"/>

<!--<link name="dummy" >

</link>
<joint name="dummy_base_link" type="fixed">
	<parent link="dummy"/>
	<child link="base_link"/>
</joint> -->
<link name="plan">
    <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
        <box size="1000 0 0"/>
    </geometry>
    </visual>
</link> 

<link name="base_link">
    <visual>
        <origin rpy="0.01 0.01 0.01" xyz="0.001 0.001 0.001"/>
        <geometry>
         <!--<cylinder length="${base_link_length}" radius="${base_link_radius}"/>  
          <box size="${width} ${length} ${higth}"/>--> 
            <mesh filename="package://ai/mesh/AMR/Assembly1.stl"/>
        </geometry>
        <material name="yellow">
            <color rgba="1 1 1 1"/>
        </material>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <!--  <box size="${width} ${length} ${higth}"/>
            <cylinder length="${base_link_length}" radius="${base_link_radius}"/> -->
             <mesh filename="package://ai/mesh/AMR/Assembly1.stl"/>
        </geometry>
    </collision>
    <inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>	
</link>

<link name="right_wheel">
    <visual>
        <origin rpy="0 ${right_wheel_rpy} 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${right_wheel_length}" radius="${right_wheel_radius}"/>
        </geometry>
    </visual>
    <collision>
        <origin rpy="0 ${right_wheel_rpy} 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${right_wheel_length}" radius="${right_wheel_radius}"/>
        </geometry>
    </collision>
    <inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>

<joint name="base_right_joint" type="continuous">
    <origin xyz="${right_joint_x} ${right_joint_y} 0 "/>
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <axes xyz="${wheel_axes} 0 0"/>
    <limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
</joint>

<link name="left_wheel">
    <visual>
    <origin rpy="0 ${-right_wheel_rpy} 0" xyz="0 0 0"/>
    <geometry>
        <cylinder length="${left_wheel_length}" radius="${left_wheel_radius}"/>
    </geometry>
    </visual>
    <collision>
    <origin rpy="0 ${-right_wheel_rpy} 0" xyz="0 0 0"/>
    <geometry>
        <cylinder length="${left_wheel_length}" radius="${left_wheel_radius}"/>
    </geometry>
    </collision>
    <inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>

<joint name="base_left_joint" type="continuous">
    <origin xyz="${-left_joint_x} ${left_joint_y} 0"/>
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <axes xyz="${wheel_axes} 0 0"/>
    <limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
</joint>

<link name="caster">
    <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
    </collision>
    <inertial>
		<mass value="${mass}"/>
		<origin xyz=" 0 0 0 "/>
		<inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
	</inertial>
</link>

<joint name="base_caster" type="continuous">
    <origin xyz="0 ${-caster_joint_y} ${-caster_joint_z}"/>
    <parent link="base_link"/>
    <child link="caster"/>
    <axes xyz="${wheel_axes} 0 0"/>
    <limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/>
</joint>

<gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo reference="caster">
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
</gazebo>
<gazebo>
	<plugin  name="differential_drive_robot" filename="libgazebo_ros_diff_drive.so">
		<robotNamespace>/</robotNamespace>
		<commandTopic>cmd_vel</commandTopic>
		<odometryTopic>odom</odometryTopic>
		<odometryFrame>odom</odometryFrame>
		<robotBaseFrame>base_link</robotBaseFrame>
		<publishWheelTF>false</publishWheelTF>
		<publishOdomTF>true</publishOdomTF>
		<publishWheelJointState>false</publishWheelJointState>
		<legacyMode>true</legacyMode>
		
		<wheelSeparation>${2*base_link_radius}</wheelSeparation>
		<wheelDiameter>${2*wheel_radius}</wheelDiameter>
		<wheelAcceleration>1.0</wheelAcceleration>
		<wheelTorque>20.0</wheelTorque>
		<updateRate>10.0</updateRate>
		<leftJoint>base_left_joint</leftJoint>
		<rightJoint>base_right_joint</rightJoint>
	</plugin>

</gazebo>
</robot> 